export const INVENTORY_DATA = {
  seeds: [
    {
      itemName: 'Wheat Seeds',
      quantityAvailable: 200,
      batchNumber: 'S-202401',
      expiryDate: '2025-03-15',
      supplier: 'AgriSeeds Ltd.',
      reorderLevel: 50,
    },
    {
      itemName: 'Rice Seeds',
      quantityAvailable: 150,
      batchNumber: 'S-202402',
      expiryDate: '2025-06-10',
      supplier: 'GreenGrow Seeds',
      reorderLevel: 30,
    },
    {
      itemName: 'Corn Seeds',
      quantityAvailable: 180,
      batchNumber: 'S-202403',
      expiryDate: '2025-02-01',
      supplier: 'FarmGen Supplies',
      reorderLevel: 40,
    },
    {
      itemName: 'Soybean Seeds',
      quantityAvailable: 300,
      batchNumber: 'S-202404',
      expiryDate: '2026-01-01',
      supplier: 'HarvestPro',
      reorderLevel: 60,
    },
    {
      itemName: 'Sunflower Seeds',
      quantityAvailable: 120,
      batchNumber: 'S-202405',
      expiryDate: '2025-05-20',
      supplier: 'AgriSeeds Ltd.',
      reorderLevel: 20,
    },
    {
      itemName: 'Cotton Seeds',
      quantityAvailable: 80,
      batchNumber: 'S-202406',
      expiryDate: '2025-12-01',
      supplier: 'SeedCo Pvt.',
      reorderLevel: 15,
    },
    {
      itemName: 'Peanut Seeds',
      quantityAvailable: 50,
      batchNumber: 'S-202407',
      expiryDate: '2025-04-15',
      supplier: 'GreenGrow Seeds',
      reorderLevel: 10,
    },
    {
      itemName: 'Millet Seeds',
      quantityAvailable: 70,
      batchNumber: 'S-202408',
      expiryDate: '2025-07-01',
      supplier: 'HarvestPro',
      reorderLevel: 15,
    },
    {
      itemName: 'Barley Seeds',
      quantityAvailable: 110,
      batchNumber: 'S-202409',
      expiryDate: '2025-08-10',
      supplier: 'FarmGen Supplies',
      reorderLevel: 25,
    },
    {
      itemName: 'Oat Seeds',
      quantityAvailable: 140,
      batchNumber: 'S-202410',
      expiryDate: '2025-09-05',
      supplier: 'SeedCo Pvt.',
      reorderLevel: 35,
    },
    {
      itemName: 'Lentil Seeds',
      quantityAvailable: 60,
      batchNumber: 'S-202411',
      expiryDate: '2025-06-01',
      supplier: 'AgriSeeds Ltd.',
      reorderLevel: 15,
    },
    {
      itemName: 'Chickpea Seeds',
      quantityAvailable: 90,
      batchNumber: 'S-202412',
      expiryDate: '2025-12-15',
      supplier: 'GreenGrow Seeds',
      reorderLevel: 20,
    },
    {
      itemName: 'Groundnut Seeds',
      quantityAvailable: 70,
      batchNumber: 'S-202413',
      expiryDate: '2025-10-10',
      supplier: 'HarvestPro',
      reorderLevel: 10,
    },
    {
      itemName: 'Pumpkin Seeds',
      quantityAvailable: 40,
      batchNumber: 'S-202414',
      expiryDate: '2025-11-25',
      supplier: 'FarmGen Supplies',
      reorderLevel: 5,
    },
    {
      itemName: 'Cucumber Seeds',
      quantityAvailable: 130,
      batchNumber: 'S-202415',
      expiryDate: '2025-12-05',
      supplier: 'SeedCo Pvt.',
      reorderLevel: 30,
    },
  ],
  fertilizers: [
    {
      itemName: 'Urea',
      quantityAvailable: 100,
      batchNumber: 'F-202401',
      expiryDate: '2025-08-01',
      supplier: 'GreenGrow Chemicals',
      reorderLevel: 20,
    },
    {
      itemName: 'NPK 10:26:26',
      quantityAvailable: 50,
      batchNumber: 'F-202402',
      expiryDate: '2025-07-15',
      supplier: 'AgroChem Ltd.',
      reorderLevel: 10,
    },
    {
      itemName: 'DAP',
      quantityAvailable: 60,
      batchNumber: 'F-202403',
      expiryDate: '2025-06-01',
      supplier: 'HarvestFert Pvt.',
      reorderLevel: 15,
    },
    {
      itemName: 'Potash',
      quantityAvailable: 80,
      batchNumber: 'F-202404',
      expiryDate: '2025-09-10',
      supplier: 'FarmChem Industries',
      reorderLevel: 20,
    },
    {
      itemName: 'Ammonium Sulfate',
      quantityAvailable: 90,
      batchNumber: 'F-202405',
      expiryDate: '2025-11-01',
      supplier: 'AgriCare Chemicals',
      reorderLevel: 25,
    },
    {
      itemName: 'Organic Manure',
      quantityAvailable: 150,
      batchNumber: 'F-202406',
      expiryDate: '2026-01-01',
      supplier: 'GreenGrow Chemicals',
      reorderLevel: 50,
    },
    {
      itemName: 'Compost',
      quantityAvailable: 200,
      batchNumber: 'F-202407',
      expiryDate: '2025-12-01',
      supplier: 'AgriBio Fertilizers',
      reorderLevel: 60,
    },
    {
      itemName: 'Gypsum',
      quantityAvailable: 70,
      batchNumber: 'F-202408',
      expiryDate: '2025-08-15',
      supplier: 'FarmGrow Chemicals',
      reorderLevel: 15,
    },
    {
      itemName: 'Superphosphate',
      quantityAvailable: 110,
      batchNumber: 'F-202409',
      expiryDate: '2025-06-10',
      supplier: 'HarvestFert Pvt.',
      reorderLevel: 25,
    },
    {
      itemName: 'Bone Meal',
      quantityAvailable: 40,
      batchNumber: 'F-202410',
      expiryDate: '2025-10-20',
      supplier: 'AgriCare Chemicals',
      reorderLevel: 5,
    },
    {
      itemName: 'Lime',
      quantityAvailable: 120,
      batchNumber: 'F-202411',
      expiryDate: '2025-11-01',
      supplier: 'GreenGrow Chemicals',
      reorderLevel: 30,
    },
    {
      itemName: 'Magnesium Sulfate',
      quantityAvailable: 50,
      batchNumber: 'F-202412',
      expiryDate: '2025-12-10',
      supplier: 'FarmChem Industries',
      reorderLevel: 10,
    },
    {
      itemName: 'Sulfur',
      quantityAvailable: 80,
      batchNumber: 'F-202413',
      expiryDate: '2026-01-20',
      supplier: 'AgriCare Chemicals',
      reorderLevel: 20,
    },
    {
      itemName: 'Muriate of Potash',
      quantityAvailable: 90,
      batchNumber: 'F-202414',
      expiryDate: '2025-08-25',
      supplier: 'HarvestFert Pvt.',
      reorderLevel: 25,
    },
    {
      itemName: 'Nitrogen Liquid',
      quantityAvailable: 100,
      batchNumber: 'F-202415',
      expiryDate: '2025-07-05',
      supplier: 'GreenGrow Chemicals',
      reorderLevel: 20,
    },
  ],
  pesticides: [
    {
      itemName: 'Glyphosate',
      quantityAvailable: 120,
      batchNumber: 'P-202401',
      expiryDate: '2025-09-01',
      supplier: 'AgriChem Solutions',
      reorderLevel: 30,
    },
    {
      itemName: 'Chlorpyrifos',
      quantityAvailable: 80,
      batchNumber: 'P-202402',
      expiryDate: '2025-07-10',
      supplier: 'GreenGuard Pesticides',
      reorderLevel: 20,
    },
    {
      itemName: 'Imidacloprid',
      quantityAvailable: 100,
      batchNumber: 'P-202403',
      expiryDate: '2025-06-05',
      supplier: 'HarvestSafe Ltd.',
      reorderLevel: 25,
    },
    {
      itemName: 'Carbaryl',
      quantityAvailable: 70,
      batchNumber: 'P-202404',
      expiryDate: '2025-11-20',
      supplier: 'AgriChem Solutions',
      reorderLevel: 15,
    },
    {
      itemName: 'Pyrethrin',
      quantityAvailable: 90,
      batchNumber: 'P-202405',
      expiryDate: '2025-12-01',
      supplier: 'GreenGuard Pesticides',
      reorderLevel: 20,
    },
    {
      itemName: 'Neem Oil',
      quantityAvailable: 150,
      batchNumber: 'P-202406',
      expiryDate: '2026-01-15',
      supplier: 'NaturalAgro Organics',
      reorderLevel: 40,
    },
    {
      itemName: 'Sulfur Dust',
      quantityAvailable: 60,
      batchNumber: 'P-202407',
      expiryDate: '2025-10-10',
      supplier: 'FarmShield',
      reorderLevel: 15,
    },
    {
      itemName: 'Copper Fungicide',
      quantityAvailable: 80,
      batchNumber: 'P-202408',
      expiryDate: '2025-09-25',
      supplier: 'HarvestSafe Ltd.',
      reorderLevel: 20,
    },
    {
      itemName: 'Bacillus Thuringiensis',
      quantityAvailable: 100,
      batchNumber: 'P-202409',
      expiryDate: '2025-08-01',
      supplier: 'NaturalAgro Organics',
      reorderLevel: 30,
    },
    {
      itemName: 'Spinosad',
      quantityAvailable: 40,
      batchNumber: 'P-202410',
      expiryDate: '2025-07-15',
      supplier: 'FarmShield',
      reorderLevel: 10,
    },
    {
      itemName: 'Rotenone',
      quantityAvailable: 60,
      batchNumber: 'P-202411',
      expiryDate: '2025-06-20',
      supplier: 'AgriChem Solutions',
      reorderLevel: 15,
    },
    {
      itemName: 'Fipronil',
      quantityAvailable: 120,
      batchNumber: 'P-202412',
      expiryDate: '2025-05-10',
      supplier: 'GreenGuard Pesticides',
      reorderLevel: 30,
    },
    {
      itemName: 'Abamectin',
      quantityAvailable: 70,
      batchNumber: 'P-202413',
      expiryDate: '2025-04-05',
      supplier: 'HarvestSafe Ltd.',
      reorderLevel: 15,
    },
    {
      itemName: 'Mancozeb',
      quantityAvailable: 110,
      batchNumber: 'P-202414',
      expiryDate: '2025-03-20',
      supplier: 'FarmShield',
      reorderLevel: 25,
    },
    {
      itemName: 'Acetamiprid',
      quantityAvailable: 90,
      batchNumber: 'P-202415',
      expiryDate: '2025-02-10',
      supplier: 'GreenGuard Pesticides',
      reorderLevel: 20,
    },
  ],
  machineryTools: [
    {
      itemName: 'Tractor',
      quantityAvailable: 10,
      model: 'John Deere 5036D',
      purchaseDate: '2023-05-15',
      supplier: 'FarmEquip Ltd.',
      condition: 'Good',
    },
    {
      itemName: 'Combine Harvester',
      quantityAvailable: 5,
      model: 'New Holland TC5.30',
      purchaseDate: '2022-11-20',
      supplier: 'HarvestTech Co.',
      condition: 'Excellent',
    },
    {
      itemName: 'Seed Drill',
      quantityAvailable: 8,
      model: 'Mahindra SD 55',
      purchaseDate: '2023-03-10',
      supplier: 'AgriEquip Supplies',
      condition: 'Good',
    },
    {
      itemName: 'Plough',
      quantityAvailable: 15,
      model: 'Lemken Opal 090',
      purchaseDate: '2024-01-05',
      supplier: 'FarmEquip Ltd.',
      condition: 'New',
    },
    {
      itemName: 'Sprayer',
      quantityAvailable: 20,
      model: 'FieldKing 16L',
      purchaseDate: '2023-08-15',
      supplier: 'AgroMach Ltd.',
      condition: 'Good',
    },
    {
      itemName: 'Cultivator',
      quantityAvailable: 12,
      model: 'FieldStar CX',
      purchaseDate: '2023-07-01',
      supplier: 'AgriEquip Supplies',
      condition: 'Good',
    },
    {
      itemName: 'Rotavator',
      quantityAvailable: 9,
      model: 'Shaktiman SRT-7',
      purchaseDate: '2023-09-20',
      supplier: 'FarmEquip Ltd.',
      condition: 'Excellent',
    },
    {
      itemName: 'Weeder',
      quantityAvailable: 18,
      model: 'Honda F300',
      purchaseDate: '2023-04-25',
      supplier: 'HarvestTech Co.',
      condition: 'Good',
    },
    {
      itemName: 'Baler',
      quantityAvailable: 4,
      model: 'Case IH SB541',
      purchaseDate: '2022-12-15',
      supplier: 'AgroMach Ltd.',
      condition: 'Excellent',
    },
    {
      itemName: 'Disc Harrow',
      quantityAvailable: 7,
      model: 'FieldKing DH5',
      purchaseDate: '2023-06-30',
      supplier: 'FarmEquip Ltd.',
      condition: 'Good',
    },
    {
      itemName: 'Power Tiller',
      quantityAvailable: 11,
      model: 'VST Shakti 130DI',
      purchaseDate: '2023-02-20',
      supplier: 'AgriEquip Supplies',
      condition: 'Good',
    },
    {
      itemName: 'Threshing Machine',
      quantityAvailable: 3,
      model: 'Massey Ferguson TH-7',
      purchaseDate: '2023-01-15',
      supplier: 'HarvestTech Co.',
      condition: 'Excellent',
    },
    {
      itemName: 'Chisel Plough',
      quantityAvailable: 6,
      model: 'Mahindra CP-4',
      purchaseDate: '2024-02-05',
      supplier: 'FarmEquip Ltd.',
      condition: 'New',
    },
    {
      itemName: 'Planter',
      quantityAvailable: 10,
      model: 'John Deere 71 Flex',
      purchaseDate: '2023-10-10',
      supplier: 'AgroMach Ltd.',
      condition: 'Good',
    },
    {
      itemName: 'Boom Sprayer',
      quantityAvailable: 5,
      model: 'FarmKing BS400',
      purchaseDate: '2023-09-15',
      supplier: 'HarvestTech Co.',
      condition: 'Excellent',
    },
  ],
};
